import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import JsonLd from "@/components/JsonLd";
import { WithContext, WebSite } from "schema-dts";

const outfit = Outfit({subsets:['latin'],variable:'--font-sans'});

const pathUrl = `https://${process.env.NEXT_PUBLIC_DOMAIN_NAME}`;

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Company Ltd",
	description: "Generated by create next app",
	openGraph: {
		title: "Company Ltd",
		description: "Generated by create next app",
		url: pathUrl,
		images: [
			{
				url: `https://${process.env.NEXT_PUBLIC_DOMAIN_NAME}/og-image.png`,
				width: 1200,
				height: 630,
			},
		],
	},
	twitter: {
		card: "summary_large_image",
		title: "Company Ltd",
		description: "Generated by create next app",
		images: [
			{
				url: `https://${process.env.NEXT_PUBLIC_DOMAIN_NAME}/og-image.png`,
				width: 1200,
				height: 630,
			},
		],
	},
	alternates: {
		canonical: pathUrl,
	},
};

const jsonLdContent: WithContext<WebSite> = {
	"@context": "https://schema.org",
	"@type": "WebSite",
	name: "Company Ltd",
	url: pathUrl,
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={outfit.variable}>
			<head>
				<JsonLd content={jsonLdContent} />
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
